import { useEffect, useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import { startAuthentication, startRegistration } from '@simplewebauthn/browser'
import bierbert from '../Bierbert/Bierbert_standard.png'
import { forgetPushUser, identifyPushUser, initializePush, requestPushPermission } from './onesignal'
import './App.css'
import './Profiles.css'

type Rsvp = 'Dabei' | 'Vielleicht' | 'Abgesagt' | 'Noch offen'
type Achievement = { id: string; title: string; icon: string }
type Person = { id: string; name: string; nickname: string; role: string; status: Rsvp; color: string; avatarUrl?: string | null; flies?: boolean; achievements?: Achievement[] }
type Invitation = { id: string; code: string; recipient: string; role: string; createdAt: string; used: boolean }
type DetailKey = 'accommodation' | 'travel' | 'meetingPoint' | 'importantInfo'
type Availability = { name: string; dates: string[] }
type LocationOption = { id: string; place: string; suggestedBy: string; votes: string[] }
type LiveEvent = { id: string; artist: string; venue: string; start: string; note: string; addedBy: string }
type UserProfile = { name: string; prefix: string; color: string; visible: boolean; flies: boolean }
type ChatMessage = { id: string; message: string; created_at: string; author: string; color: string }
type Highlight = { id: string; title: string; created_at: string; author: string; imageUrl: string }
type PastTrip = { id: string; title: string; destination: string; start_date: string; end_date: string; note: string }
type InstallPrompt = Event & { prompt: () => Promise<void>; userChoice: Promise<{ outcome: 'accepted' | 'dismissed' }> }
type FlightLeg = { date: string; time: string; airport: string; terminal: string; gate: string; flightNumber: string }
type FlightPlan = { outbound: FlightLeg; return: FlightLeg; airportMeetingTime: string }
type AccountProfile = { id: string; name: string; role: string; visible: boolean }
type Trip = { title: string; destination: string; startDate: string; endDate: string; accommodation: string; accommodationDetails: string; travel: string; travelDetails: string; flightPlan: FlightPlan; meetingPoint: string; meetingPointDetails: string; importantInfo: string; importantInfoDetails: string; planningMeeting: string; notes: string; participants: Person[]; invitations: Invitation[]; availabilities: Availability[]; locationOptions: LocationOption[]; liveEvents: LiveEvent[]; myProfile: UserProfile }

const STORAGE_KEY = 'malle-hq-trip-data-v2'
const SESSION_KEY = 'malle-hq-session-v1'
const ONBOARDING_KEY = 'malle-hq-onboarding-v1'
const API_BASE = import.meta.env.VITE_API_URL || ''
const colors = ['#ff6b35', '#168aad', '#8f5bd7', '#22a66f', '#e48b18', '#d9578e']
const defaults: Trip = {
  title: 'Malle 2027', destination: 'Palma de Mallorca', startDate: '2027-05-18T06:00', endDate: '2027-05-22T18:00',
  accommodation: 'Hotel an der Playa de Palma · Details folgen', accommodationDetails: 'Unser Basecamp liegt direkt an der Playa de Palma. Hier kann der Harte Kern später Adresse, Check-in-Zeit, Zimmeraufteilung und alle weiteren Hotelinfos hinterlegen.', travel: 'Gemeinsamer Hinflug am 18. Mai · Treffpunkt 04:15 Uhr am Flughafen', travelDetails: 'Alle Angaben zu Gepäck, Transfer und weitere Hinweise zur Reise kommen hier hinein.', flightPlan: { outbound: { date: '2027-05-18', time: '06:00', airport: '', terminal: '', gate: '', flightNumber: '' }, return: { date: '2027-05-22', time: '18:00', airport: 'Palma de Mallorca', terminal: '', gate: '', flightNumber: '' }, airportMeetingTime: '04:15' }, meetingPoint: 'Terminal 1 · vor dem Check-in-Schalter', meetingPointDetails: 'Wir treffen uns rechtzeitig vor dem Check-in. Der genaue Bereich, eine Kontaktperson und Hinweise für Nachzügler können vom Harten Kern hier ergänzt werden.', importantInfo: 'Ausweis, Sonnencreme und gute Laune nicht vergessen. Flugunterlagen kommen in die Gruppe.', importantInfoDetails: 'Packliste, Dokumente, gemeinsame Absprachen und alles, was wirklich niemand vergessen darf. Der Harte Kern pflegt hier die vollständigen Informationen.', notes: 'Zimmeraufteilung und gemeinsamer Transfer werden noch abgestimmt.',
  planningMeeting: 'Gemeinsam Termin und Treffpunkt für unser Planungstreffen finden.', participants: [], invitations: [], availabilities: [], locationOptions: [], liveEvents: [], myProfile: { name: 'Malle-Fan', prefix: '', color: colors[2], visible: true, flies: false },
}
const profilePrefixes = ['', 'Promille-', 'Säulenjäger-', 'Biervernichter-', 'Theken-', 'Sangria-', 'Party-', 'Durst-', 'König-', 'Abriss-']
const achievementPresets = [{ icon: '🍹', title: 'Bamboleo-Stammgast' }, { icon: '🎉', title: 'Megapark-Dauergast' }, { icon: '🍻', title: 'Bester Trinker' }, { icon: '✈️', title: 'Jährlicher Stammflieger' }, { icon: '👑', title: 'König der Playa' }, { icon: '🌅', title: 'Säulen-Frühschicht' }, { icon: '🥴', title: 'Letzter Mensch im Bierkönig' }, { icon: '🌴', title: 'Malle-Inventar' }]
const heroQuestions = ['Bereit für Malle?', 'Wächst die Vorfreude bereits?', 'Trainierst du schon fleißig?', 'Ist die Leber schon im Trainingslager?', 'Sitzt die Sonnenbrille?', 'Schon den ersten Sangria im Kopf?']
const onboardingSteps = [
  { icon: '👋', title: 'Willkommen im Malle HQ!', text: 'Ich bin Bierbert. Ich zeige dir kurz, wo die wichtigen Sachen und der gepflegte Unsinn wohnen.' },
  { icon: '🗂️', title: 'Alle Cards führen weiter', text: 'Tippe auf Unterkunft, Anreise, Planung oder Auftritte – jede Card hat ihre eigene Detailseite.' },
  { icon: '😎', title: 'Dein offizieller Malle-Name', text: 'Im Profil baust du dir deinen Anzeigenamen, lädst ein Bild hoch und entscheidest, ob du in der Crew sichtbar bist.' },
  { icon: '🎟️', title: 'Jetzt noch richtig einchecken', text: 'Mit deinem Einladungscode legst du gleich Name und Passwort fest. Erst danach sieht die Crew dein Profil – Bierberts Einführung allein meldet dich noch nicht an.' },
]
const makeId = () => `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`
const initials = (name: string) => name.trim().split(/\s+/).map(word => word[0]).join('').slice(0, 2).toUpperCase() || '?'
function loadTrip(): Trip { try { const saved = localStorage.getItem(STORAGE_KEY); return saved ? { ...defaults, ...JSON.parse(saved) } : defaults } catch { return defaults } }
async function api(path: string, options: RequestInit = {}) {
  const token = localStorage.getItem(SESSION_KEY)
  const response = await fetch(`${API_BASE}${path}`, { ...options, headers: { ...(options.body instanceof Blob ? {} : { 'Content-Type': 'application/json' }), ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } })
  const data = await response.json().catch(() => ({}))
  if (!response.ok) throw new Error(data.error || 'Das hat nicht geklappt.')
  return data
}
function getCountdown(date: string) { const distance = Math.max(0, new Date(date).getTime() - Date.now()); return { days: Math.floor(distance / 86_400_000), hours: Math.floor(distance / 3_600_000 % 24), minutes: Math.floor(distance / 60_000 % 60), seconds: Math.floor(distance / 1_000 % 60) } }
const formatDate = (date: string, options: Intl.DateTimeFormatOptions) => new Intl.DateTimeFormat('de-DE', options).format(new Date(date))

function App() {
  const [trip, setTrip] = useState<Trip>(loadTrip), [countdown, setCountdown] = useState(() => getCountdown(trip.startDate))
  const [loginOpen, setLoginOpen] = useState(false), [admin, setAdmin] = useState(false), [loginName, setLoginName] = useState(''), [password, setPassword] = useState(''), [setupCode, setSetupCode] = useState(''), [setupDisplayName, setSetupDisplayName] = useState(''), [setupRequired, setSetupRequired] = useState(false), [error, setError] = useState('')
  const [selectedPerson, setSelectedPerson] = useState<Person | null>(null), [selectedDetail, setSelectedDetailState] = useState<DetailKey | 'planning' | 'live' | 'chat' | 'highlights' | 'archive' | 'profiles' | null>(null), [inviteOpen, setInviteOpen] = useState(false), [inviteCode, setInviteCode] = useState(''), [inviteName, setInviteName] = useState(''), [inviteNickname, setInviteNickname] = useState(''), [inviteLoginName, setInviteLoginName] = useState(''), [invitePassword, setInvitePassword] = useState(''), [inviteStatus, setInviteStatus] = useState<Rsvp>('Dabei'), [inviteFlies, setInviteFlies] = useState(true), [newRecipient, setNewRecipient] = useState(''), [newInviteRole, setNewInviteRole] = useState('Crewmitglied'), [copied, setCopied] = useState('')
  const [chosenDates, setChosenDates] = useState<string[]>([]), [placeSuggestion, setPlaceSuggestion] = useState(''), [profileEditOpen, setProfileEditOpen] = useState(false), [draftName, setDraftName] = useState(trip.myProfile.name), [draftPrefix, setDraftPrefix] = useState(trip.myProfile.prefix), [draftVisible, setDraftVisible] = useState(trip.myProfile.visible ?? true), [draftFlies, setDraftFlies] = useState(trip.myProfile.flies ?? false)
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([]), [chatText, setChatText] = useState(''), [extrasAuthenticated, setExtrasAuthenticated] = useState(false)
  const [highlights, setHighlights] = useState<Highlight[]>([]), [highlightTitle, setHighlightTitle] = useState(''), [highlightFile, setHighlightFile] = useState<File | null>(null)
  const [pastTrips, setPastTrips] = useState<PastTrip[]>([]), [pastTitle, setPastTitle] = useState(''), [pastDestination, setPastDestination] = useState(''), [pastStart, setPastStart] = useState(''), [pastEnd, setPastEnd] = useState(''), [pastNote, setPastNote] = useState('')
  const [onboardingStep, setOnboardingStep] = useState<number | null>(() => localStorage.getItem(ONBOARDING_KEY) ? null : 0)
  const [calendarMonth, setCalendarMonth] = useState(() => { const date = new Date(); date.setDate(1); date.setHours(12, 0, 0, 0); return date }), [eventArtist, setEventArtist] = useState(''), [eventVenue, setEventVenue] = useState('Bierkönig'), [eventStart, setEventStart] = useState(''), [eventNote, setEventNote] = useState('')
  const [heroQuestion] = useState(() => heroQuestions[Math.floor(Math.random() * heroQuestions.length)])
  const [installPrompt, setInstallPrompt] = useState<InstallPrompt | null>(null), [installHelpOpen, setInstallHelpOpen] = useState(false), [pushEnabled, setPushEnabled] = useState(false), [profileId, setProfileId] = useState('')
  const [flightDraft, setFlightDraft] = useState<FlightPlan>(trip.flightPlan), [travelSaved, setTravelSaved] = useState(false)
  const [passkeyBusy, setPasskeyBusy] = useState(false), [achievementTitle, setAchievementTitle] = useState(''), [achievementIcon, setAchievementIcon] = useState('🏆')
  const [accountProfiles, setAccountProfiles] = useState<AccountProfile[]>([]), [resetCodes, setResetCodes] = useState<Record<string, string>>({})
  const [forgotOpen, setForgotOpen] = useState(false), [recoveryCode, setRecoveryCode] = useState(''), [recoveryPassword, setRecoveryPassword] = useState(''), [recoveryConfirm, setRecoveryConfirm] = useState('')
  const [changePasswordOpen, setChangePasswordOpen] = useState(false), [currentPassword, setCurrentPassword] = useState(''), [newPassword, setNewPassword] = useState(''), [newPasswordConfirm, setNewPasswordConfirm] = useState('')
  const setSelectedDetail = (detail: DetailKey | 'planning' | 'live' | 'chat' | 'highlights' | 'archive' | 'profiles' | null) => { if (detail === 'travel') setFlightDraft(trip.flightPlan || defaults.flightPlan); setSelectedDetailState(detail) }
  useEffect(() => { const timer = setInterval(() => setCountdown(getCountdown(trip.startDate)), 1000); return () => clearInterval(timer) }, [trip.startDate])
  useEffect(() => { localStorage.setItem(STORAGE_KEY, JSON.stringify(trip)) }, [trip])
  const loadExtras = async () => { if (!API_BASE) return; try { const data = await api('/extras'); setChatMessages(data.chat || []); setHighlights(data.highlights || []); setPastTrips(data.pastTrips || []); setExtrasAuthenticated(Boolean(data.authenticated)) } catch { setExtrasAuthenticated(false) } }
  useEffect(() => { initializePush(setPushEnabled); if (!API_BASE) return; api('/state').then(data => { if (data.content) setTrip(current => ({ ...current, ...data.content, participants: data.participants || [], myProfile: data.profile ? { name: data.profile.name, prefix: data.profile.prefix, color: data.profile.color, visible: Boolean(data.profile.visible), flies: Boolean(data.profile.flies) } : current.myProfile })); setProfileId(data.profile?.id || ''); setAdmin(Boolean(data.isAdmin)); setAccountProfiles(data.accountProfiles || []); setSetupRequired(Boolean(data.setupRequired)); void loadExtras() }).catch(() => setError('Cloud-Verbindung gerade nicht erreichbar.')) }, [])
  useEffect(() => { if (profileId) identifyPushUser(profileId) }, [profileId])
  useEffect(() => { if (!extrasAuthenticated) return; const timer = window.setInterval(() => void loadExtras(), 20_000); return () => window.clearInterval(timer) }, [extrasAuthenticated])
  useEffect(() => { const receivePrompt = (event: Event) => { event.preventDefault(); setInstallPrompt(event as InstallPrompt) }; window.addEventListener('beforeinstallprompt', receivePrompt); return () => window.removeEventListener('beforeinstallprompt', receivePrompt) }, [])
  useEffect(() => { const plane = document.querySelector('.plane-body'); if (!plane || !('IntersectionObserver' in window) || window.matchMedia('(prefers-reduced-motion: reduce)').matches) return; plane.classList.add('waiting'); const observer = new IntersectionObserver(entries => { if (entries.some(entry => entry.isIntersecting)) { plane.classList.remove('waiting'); plane.classList.add('fly-in'); observer.disconnect() } }, { threshold: 0.25 }); observer.observe(plane); return () => observer.disconnect() }, [])
  const duration = useMemo(() => { const start = Date.parse(`${trip.startDate.slice(0, 10)}T00:00:00Z`), end = Date.parse(`${trip.endDate.slice(0, 10)}T00:00:00Z`), nights = Math.max(1, Math.round((end - start) / 86_400_000)); return `${nights} ${nights === 1 ? 'Nacht' : 'Nächte'}` }, [trip.endDate, trip.startDate])
  const displayName = `${trip.myProfile.prefix}${trip.myProfile.name}`
  const flyers = trip.participants.filter(person => person.flies)
  const ownProfile = profileId ? trip.participants.find(person => person.id === profileId) || { id: profileId, name: displayName, nickname: '', role: admin ? 'Harter Kern' : 'Crewmitglied', status: 'Dabei' as Rsvp, color: trip.myProfile.color, flies: trip.myProfile.flies, achievements: [] } : null
  const galleryProfiles = profileId ? trip.participants.filter(person => person.id !== profileId) : trip.participants
  const saveCloud = async (next: Trip) => { if (!API_BASE || !localStorage.getItem(SESSION_KEY)) return; try { await api('/state', { method: 'PUT', body: JSON.stringify(next) }) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Speichern fehlgeschlagen.') } }
  const update = <K extends keyof Trip>(key: K, value: Trip[K]) => { setTrip(current => { const next = { ...current, [key]: value }; void saveCloud(next); return next }) }
  const login = async (event: FormEvent) => { event.preventDefault(); try { const data = setupRequired ? await api('/setup-owner', { method: 'POST', body: JSON.stringify({ setupCode, loginName, password, displayName: setupDisplayName }) }) : await api('/login', { method: 'POST', body: JSON.stringify({ loginName, password }) }); localStorage.setItem(SESSION_KEY, data.token); setAdmin(data.role === 'Harter Kern'); setSetupRequired(false); setLoginOpen(false); setPassword(''); setSetupCode(''); setError(''); const fresh = await api('/state'); setProfileId(fresh.profile?.id || ''); setAccountProfiles(fresh.accountProfiles || []); await api('/state', { method: 'PUT', body: JSON.stringify(trip) }); await loadExtras() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Anmeldung fehlgeschlagen.') } }
  const loginWithPasskey = async () => { if (!loginName.trim()) { setError('Bitte zuerst deinen Login-Namen eingeben.'); return } setPasskeyBusy(true); try { const start = await api('/passkeys/authenticate/options', { method: 'POST', body: JSON.stringify({ loginName }) }); const response = await startAuthentication({ optionsJSON: start.options }); const data = await api('/passkeys/authenticate/verify', { method: 'POST', body: JSON.stringify({ profileId: start.profileId, response }) }); localStorage.setItem(SESSION_KEY, data.token); const fresh = await api('/state'); setTrip(current => ({ ...current, ...fresh.content, participants: fresh.participants || [], myProfile: { name: fresh.profile.name, prefix: fresh.profile.prefix, color: fresh.profile.color, visible: Boolean(fresh.profile.visible), flies: Boolean(fresh.profile.flies) } })); setProfileId(fresh.profile.id); setAdmin(data.role === 'Harter Kern'); setLoginOpen(false); setError(''); await loadExtras() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Passkey-Anmeldung abgebrochen.') } finally { setPasskeyBusy(false) } }
  const registerPasskey = async () => { setPasskeyBusy(true); try { const options = await api('/passkeys/register/options', { method: 'POST', body: '{}' }); const response = await startRegistration({ optionsJSON: options }); await api('/passkeys/register/verify', { method: 'POST', body: JSON.stringify({ response }) }); setError('Passkey eingerichtet ✓ Beim nächsten Mal genügen Fingerabdruck, Gesicht oder Gerätecode.') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Passkey konnte nicht eingerichtet werden.') } finally { setPasskeyBusy(false) } }
  const logout = async () => { try { await api('/logout', { method: 'POST', body: '{}' }) } catch { /* lokal trotzdem ausloggen */ } localStorage.removeItem(SESSION_KEY); forgetPushUser(); setAdmin(false); setProfileId(''); setExtrasAuthenticated(false); setProfileEditOpen(false); const fresh = await api('/state'); setTrip(current => ({ ...current, ...fresh.content, participants: fresh.participants || [], myProfile: defaults.myProfile })); setLoginOpen(true); setError('Du bist ausgeloggt.') }
  const awardAchievement = async () => { if (!selectedPerson || !achievementTitle.trim()) return; try { const data = await api('/achievements', { method: 'POST', body: JSON.stringify({ profileId: selectedPerson.id, title: achievementTitle, icon: achievementIcon }) }); const badge = { id: data.id, title: achievementTitle.trim(), icon: achievementIcon }; setSelectedPerson(current => current ? { ...current, achievements: [badge, ...(current.achievements || [])] } : current); setTrip(current => ({ ...current, participants: current.participants.map(person => person.id === selectedPerson.id ? { ...person, achievements: [badge, ...(person.achievements || [])] } : person) })); setAchievementTitle('') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Auszeichnung konnte nicht vergeben werden.') } }
  const changePassword = async (event: FormEvent) => { event.preventDefault(); if (newPassword !== newPasswordConfirm) { setError('Die neuen Passwörter stimmen nicht überein.'); return } try { await api('/password/change', { method: 'POST', body: JSON.stringify({ currentPassword, newPassword }) }); setCurrentPassword(''); setNewPassword(''); setNewPasswordConfirm(''); setChangePasswordOpen(false); setError('Passwort geändert ✓ Du bleibst auf diesem Gerät angemeldet.') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Passwort konnte nicht geändert werden.') } }
  const generatePasswordReset = async (target: AccountProfile) => { try { const data = await api('/password-resets', { method: 'POST', body: JSON.stringify({ profileId: target.id }) }); setResetCodes(current => ({ ...current, [target.id]: data.code })); setError('') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Code konnte nicht erstellt werden.') } }
  const redeemPasswordReset = async (event: FormEvent) => { event.preventDefault(); if (recoveryPassword !== recoveryConfirm) { setError('Die neuen Passwörter stimmen nicht überein.'); return } try { const data = await api('/password-resets/redeem', { method: 'POST', body: JSON.stringify({ code: recoveryCode, newPassword: recoveryPassword }) }); localStorage.setItem(SESSION_KEY, data.token); const fresh = await api('/state'); setTrip(current => ({ ...current, ...fresh.content, participants: fresh.participants || [], myProfile: { name: fresh.profile.name, prefix: fresh.profile.prefix, color: fresh.profile.color, visible: Boolean(fresh.profile.visible), flies: Boolean(fresh.profile.flies) } })); setProfileId(fresh.profile.id); setAdmin(data.role === 'Harter Kern'); setAccountProfiles(fresh.accountProfiles || []); setForgotOpen(false); setRecoveryCode(''); setRecoveryPassword(''); setRecoveryConfirm(''); setError('Passwort erneuert ✓ Du bist wieder eingeloggt.') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Wiederherstellung fehlgeschlagen.') } }
  const createInvite = async () => { try { const invitation = await api('/invitations', { method: 'POST', body: JSON.stringify({ recipient: newRecipient, role: newInviteRole }) }); setTrip(current => ({ ...current, invitations: [{ id: makeId(), code: invitation.code, recipient: invitation.recipient, role: invitation.role, createdAt: new Date().toISOString(), used: false }, ...current.invitations] })); setNewRecipient(''); setError('') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Einladung konnte nicht erstellt werden.') } }
  const copyInvite = async (code: string) => { try { await navigator.clipboard.writeText(`Du bist bei ${trip.title} dabei! Öffne ${window.location.origin}${import.meta.env.BASE_URL} und nutze deinen Einladungscode: ${code}`); setCopied(code); setTimeout(() => setCopied(''), 1800) } catch { setCopied('') } }
  const checkInvite = () => { if (!inviteCode.trim().toUpperCase().startsWith('MALLE-')) { setError('Der Einladungscode beginnt mit MALLE-.'); return } setError(''); setInviteCode(inviteCode.trim().toUpperCase()) }
  const acceptInvite = async (event: FormEvent) => { event.preventDefault(); if (!inviteName.trim()) { setError('Bitte trag deinen Namen ein.'); return } try { const color = colors[trip.participants.length % colors.length]; const data = await api('/invitations/accept', { method: 'POST', body: JSON.stringify({ code: inviteCode, name: inviteName, nickname: inviteNickname, loginName: inviteLoginName, password: invitePassword, status: inviteStatus, flies: inviteFlies, color }) }); localStorage.setItem(SESSION_KEY, data.token); const fresh = await api('/state'); setTrip(current => ({ ...current, ...fresh.content, participants: fresh.participants, myProfile: { name: fresh.profile.name, prefix: fresh.profile.prefix, color: fresh.profile.color, visible: Boolean(fresh.profile.visible), flies: Boolean(fresh.profile.flies) } })); setProfileId(fresh.profile.id); setAdmin(data.role === 'Harter Kern'); await loadExtras(); setInviteOpen(false); setInviteName(''); setInviteNickname(''); setInviteLoginName(''); setInvitePassword(''); setError('') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Einladung konnte nicht eingelöst werden.') } }
  const finishOnboarding = () => { localStorage.setItem(ONBOARDING_KEY, 'done'); setOnboardingStep(null) }
  const inviteIsValid = /^MALLE-[A-F0-9]{8}$/.test(inviteCode.trim().toUpperCase())
  const labels: Record<string, string> = { days: 'Tage', hours: 'Std.', minutes: 'Min.', seconds: 'Sek.' }
  const detailCards: { key: DetailKey; icon: string; label: string; title: string; color: string; detailKey: keyof Trip }[] = [
    { key: 'accommodation', icon: '🏨', label: 'Unterkunft', title: 'Unser Basecamp', color: 'coral', detailKey: 'accommodationDetails' },
    { key: 'travel', icon: '✈️', label: 'Anreise', title: 'Ab auf die Insel', color: 'blue', detailKey: 'travelDetails' },
    { key: 'meetingPoint', icon: '📍', label: 'Treffpunkt', title: 'Hier geht’s los', color: 'yellow', detailKey: 'meetingPointDetails' },
    { key: 'importantInfo', icon: '📣', label: 'Wichtig', title: 'Auf dem Schirm', color: 'mint', detailKey: 'importantInfoDetails' },
  ]
  const activeDetail = detailCards.find(card => card.key === selectedDetail)
  const daysInMonth = new Date(calendarMonth.getFullYear(), calendarMonth.getMonth() + 1, 0).getDate()
  const monthOffset = (new Date(calendarMonth.getFullYear(), calendarMonth.getMonth(), 1).getDay() + 6) % 7
  const calendarDays = Array.from({ length: daysInMonth }, (_, index) => new Date(calendarMonth.getFullYear(), calendarMonth.getMonth(), index + 1, 12))
  const allChosenDates = [...new Set(trip.availabilities.flatMap(entry => entry.dates))]
  const dateResults = allChosenDates.map(iso => ({ iso, date: new Date(`${iso}T12:00:00`), names: trip.availabilities.filter(entry => entry.dates.includes(iso)).map(entry => entry.name) })).sort((a, b) => b.names.length - a.names.length || a.iso.localeCompare(b.iso))
  const toggleDate = (iso: string) => setChosenDates(current => current.includes(iso) ? current.filter(date => date !== iso) : [...current, iso])
  const saveAvailability = () => { if (!chosenDates.length) return; update('availabilities', [...trip.availabilities.filter(entry => entry.name !== displayName), { name: displayName, dates: chosenDates }]); setChosenDates([]) }
  const suggestPlace = () => { if (!placeSuggestion.trim()) return; update('locationOptions', [...trip.locationOptions, { id: makeId(), place: placeSuggestion.trim(), suggestedBy: displayName, votes: [displayName] }]); setPlaceSuggestion('') }
  const votePlace = (id: string) => update('locationOptions', trip.locationOptions.map(option => option.id !== id ? option : { ...option, votes: option.votes.includes(displayName) ? option.votes.filter(name => name !== displayName) : [...option.votes, displayName] }))
  const moveMonth = (amount: number) => setCalendarMonth(current => new Date(current.getFullYear(), current.getMonth() + amount, 1, 12))
  const addLiveEvent = () => { if (!eventArtist.trim() || !eventStart) return; const event: LiveEvent = { id: makeId(), artist: eventArtist.trim(), venue: eventVenue.trim() || 'Noch offen', start: eventStart, note: eventNote.trim(), addedBy: displayName }; update('liveEvents', [...trip.liveEvents, event]); setEventArtist(''); setEventStart(''); setEventNote('') }
  const sortedLiveEvents = [...trip.liveEvents].sort((a, b) => new Date(a.start).getTime() - new Date(b.start).getTime())
  const openProfileEditor = () => { if (!profileId) { setLoginOpen(true); return } setDraftName(trip.myProfile.name); setDraftPrefix(trip.myProfile.prefix); setDraftVisible(trip.myProfile.visible ?? true); setDraftFlies(trip.myProfile.flies ?? false); setProfileEditOpen(true) }
  const saveProfile = async (event: FormEvent) => { event.preventDefault(); if (!draftName.trim()) return; try { await api('/profile', { method: 'PATCH', body: JSON.stringify({ name: draftName.trim(), prefix: draftPrefix, color: trip.myProfile.color, visible: draftVisible, flies: draftFlies }) }); const oldName = displayName, nextProfile = { ...trip.myProfile, name: draftName.trim(), prefix: draftPrefix, visible: draftVisible, flies: draftFlies }, nextName = `${draftPrefix}${draftName.trim()}`; const fresh = await api('/state'); setTrip(current => ({ ...current, myProfile: nextProfile, participants: fresh.participants, availabilities: current.availabilities.map(entry => entry.name === oldName ? { ...entry, name: nextName } : entry), locationOptions: current.locationOptions.map(option => ({ ...option, suggestedBy: option.suggestedBy === oldName ? nextName : option.suggestedBy, votes: option.votes.map(name => name === oldName ? nextName : name) })), liveEvents: current.liveEvents.map(item => item.addedBy === oldName ? { ...item, addedBy: nextName } : item) })); setProfileEditOpen(false); setError('') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Profil konnte nicht gespeichert werden.') } }
  const uploadAvatar = async (file?: File) => { if (!file) return; try { await api('/profile/avatar', { method: 'PUT', body: file, headers: { 'Content-Type': file.type } }); const fresh = await api('/state'); setTrip(current => ({ ...current, participants: fresh.participants })); setError('') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Profilbild konnte nicht gespeichert werden.') } }
  const sendChat = async (event: FormEvent) => { event.preventDefault(); if (!chatText.trim()) return; try { await api('/chat', { method: 'POST', body: JSON.stringify({ message: chatText }) }); setChatText(''); await loadExtras() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Nachricht konnte nicht gesendet werden.') } }
  const addHighlight = async (event: FormEvent) => { event.preventDefault(); if (!highlightTitle.trim() || !highlightFile) return; try { await api(`/highlights?title=${encodeURIComponent(highlightTitle.trim())}`, { method: 'POST', body: highlightFile, headers: { 'Content-Type': highlightFile.type } }); setHighlightTitle(''); setHighlightFile(null); await loadExtras() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Highlight konnte nicht gespeichert werden.') } }
  const addPastTrip = async (event: FormEvent) => { event.preventDefault(); try { await api('/past-trips', { method: 'POST', body: JSON.stringify({ title: pastTitle, destination: pastDestination, startDate: pastStart, endDate: pastEnd, note: pastNote }) }); setPastTitle(''); setPastDestination(''); setPastStart(''); setPastEnd(''); setPastNote(''); await loadExtras() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Reise konnte nicht archiviert werden.') } }
  const installApp = async () => { if (installPrompt) { await installPrompt.prompt(); const choice = await installPrompt.userChoice; if (choice.outcome === 'accepted') setInstallPrompt(null) } else setInstallHelpOpen(true) }
  const enablePush = () => requestPushPermission(allowed => { setPushEnabled(allowed); if (!allowed) setError('Push wurde nicht erlaubt. Du kannst es später in den Browser-Einstellungen freigeben.') })
  const changeFlight = (leg: 'outbound' | 'return', field: keyof FlightLeg, value: string) => { setTravelSaved(false); setFlightDraft(current => ({ ...current, [leg]: { ...current[leg], [field]: value } })) }
  const saveFlightPlan = async () => { const startDate = `${flightDraft.outbound.date}T${flightDraft.outbound.time || '00:00'}`, endDate = `${flightDraft.return.date}T${flightDraft.return.time || '00:00'}`; const next = { ...trip, flightPlan: flightDraft, startDate, endDate, travel: flightDraft.outbound.date ? `Hinflug am ${formatDate(startDate, { day: 'numeric', month: 'long', hour: '2-digit', minute: '2-digit' })} Uhr${flightDraft.outbound.airport ? ` ab ${flightDraft.outbound.airport}` : ''}` : trip.travel }; setTrip(next); await saveCloud(next); setTravelSaved(true) }

  if (selectedDetail === 'live') return <main className="app-shell detail-page live-page">
    <header className="topbar"><button className="back-button" onClick={() => setSelectedDetail(null)}>← <span>Zurück</span></button><span className="brand"><span className="brand-mark">MHQ</span><span>Malle HQ</span></span></header>
    <section className="detail-hero live-color"><span className="detail-hero-icon">🎤</span><p className="eyebrow">Malle-Live-Auftritte</p><h1>Wer spielt wann?</h1><p>Bestätigte Acts für eure Reisetage – automatisch in der richtigen zeitlichen Reihenfolge.</p></section>
    <section className="live-content"><div className="source-note"><span>🔎</span><div><strong>Programm für Mai 2027 noch nicht veröffentlicht</strong><p>Schaut später in die offiziellen Tagesprogramme und tragt bestätigte Auftritte hier ein.</p><div><a href="https://www.bierkoenig.com/?post_type=event" target="_blank" rel="noreferrer">Bierkönig-Programm ↗</a><a href="https://www.megapark.tv/de" target="_blank" rel="noreferrer">Megapark-Programm ↗</a></div></div></div>
      <div className="live-heading"><p className="eyebrow">Unser Zeitplan</p><h2>Live auf Malle</h2></div>{sortedLiveEvents.length ? <div className="live-timeline">{sortedLiveEvents.map(event => <article key={event.id}><div className="timeline-date"><strong>{formatDate(event.start, { day: '2-digit' })}</strong><span>{formatDate(event.start, { month: 'short' })}</span></div><div className="timeline-line" /><div className="event-card"><p>{formatDate(event.start, { weekday: 'long', hour: '2-digit', minute: '2-digit' })} Uhr</p><h3>{event.artist}</h3><strong>📍 {event.venue}</strong>{event.note && <span>{event.note}</span>}<small>Eingetragen von {event.addedBy}</small>{admin && <button onClick={() => update('liveEvents', trip.liveEvents.filter(item => item.id !== event.id))}>Entfernen</button>}</div></article>)}</div> : <p className="empty-state">Noch keine bestätigten Auftritte eingetragen.</p>}
      <div className="planner-divider" /><div className="planner-heading"><span>+</span><div><p className="eyebrow">Crew-Eintrag</p><h2>Auftritt hinzufügen</h2></div></div><div className="event-form"><label>Act / Künstler<input placeholder="z. B. Peter Wackel" value={eventArtist} onChange={e => setEventArtist(e.target.value)} /></label><label>Location<select value={eventVenue} onChange={e => setEventVenue(e.target.value)}><option>Bierkönig</option><option>Megapark</option><option>Oberbayern</option><option>Bamboleo</option><option>Andere Location</option></select></label><label>Datum und Uhrzeit<input type="datetime-local" value={eventStart} onChange={e => setEventStart(e.target.value)} /></label><label>Hinweis <small>optional</small><input placeholder="Eintritt, Treffpunkt …" value={eventNote} onChange={e => setEventNote(e.target.value)} /></label></div><button className="save-button" disabled={!eventArtist.trim() || !eventStart} onClick={addLiveEvent}>Auftritt eintragen</button><button className="back-cta live-back" onClick={() => setSelectedDetail(null)}>← Zur Startseite</button></section>
  </main>

  if (selectedDetail === 'planning') return <main className="app-shell detail-page planning-page">
    <header className="topbar"><button className="back-button" onClick={() => setSelectedDetail(null)}>← <span>Zurück</span></button><span className="brand"><span className="brand-mark">MHQ</span><span>Malle HQ</span></span></header>
    <section className="detail-hero planning-color"><span className="detail-hero-icon">🗓️</span><p className="eyebrow">Planungstreffen</p><h1>Wann passt’s?</h1><p>{trip.planningMeeting}</p></section>{admin && <label className="inline-editor planning-intro-editor">Einleitung bearbeiten<textarea rows={3} value={trip.planningMeeting} onChange={e => update('planningMeeting', e.target.value)} /></label>}
    <section className="planning-content"><div className="planner-heading"><span>1</span><div><p className="eyebrow">Verfügbarkeit</p><h2>Wann kannst du?</h2></div></div><div className="active-profile"><span className="avatar" style={{ background: trip.myProfile.color }}>{initials(displayName)}</span><span><small>Du stimmst ab als</small><strong>{displayName}</strong></span><button onClick={openProfileEditor}>Ändern</button></div><div className="month-navigation"><button onClick={() => moveMonth(-1)}>←</button><strong>{formatDate(calendarMonth.toISOString(), { month: 'long', year: 'numeric' })}</strong><button onClick={() => moveMonth(1)}>→</button></div><div className="calendar-weekdays">{['Mo','Di','Mi','Do','Fr','Sa','So'].map(day => <span key={day}>{day}</span>)}</div><div className="availability-calendar">{Array.from({ length: monthOffset }, (_, index) => <span className="calendar-blank" key={`blank-${index}`} />)}{calendarDays.map(date => { const iso = date.toISOString().slice(0, 10), active = chosenDates.includes(iso), votes = trip.availabilities.filter(entry => entry.dates.includes(iso)).length; return <button className={active ? 'chosen' : ''} key={iso} onClick={() => toggleDate(iso)}><strong>{date.getDate()}</strong>{votes > 0 && <small>{votes} ✓</small>}</button> })}</div><button className="save-button planner-save" disabled={!chosenDates.length} onClick={saveAvailability}>Meine Auswahl speichern</button>
      <div className="planner-divider" /><div className="planner-heading"><span>2</span><div><p className="eyebrow">Abstimmung</p><h2>Das passt der Crew</h2></div></div>{dateResults.length ? <div className="date-results">{dateResults.map((result, index) => <div className={`result-row ${index === 0 ? 'winner' : ''}`} key={result.iso}><div className="result-date"><strong>{formatDate(result.iso, { day: '2-digit' })}</strong><span>{formatDate(result.iso, { month: 'short' })}</span></div><div><strong>{formatDate(result.iso, { weekday: 'long' })}</strong><small>{result.names.join(', ')}</small></div><b>{result.names.length} {result.names.length === 1 ? 'Stimme' : 'Stimmen'}</b></div>)}</div> : <p className="empty-state">Noch keine Auswahl gespeichert. Du kannst den Anfang machen.</p>}
      <div className="planner-divider" /><div className="planner-heading"><span>3</span><div><p className="eyebrow">Treffpunkt</p><h2>Wo treffen wir uns?</h2></div></div><div className="place-create"><input placeholder="z. B. Biergarten am See" value={placeSuggestion} onChange={e => setPlaceSuggestion(e.target.value)} /><button className="save-button" disabled={!placeSuggestion.trim()} onClick={suggestPlace}>Vorschlagen</button></div><div className="place-options">{trip.locationOptions.map(option => <button className={option.votes.includes(displayName) ? 'voted' : ''} key={option.id} onClick={() => votePlace(option.id)}><span>📍</span><span><strong>{option.place}</strong><small>Vorschlag von {option.suggestedBy}</small></span><b>♥ {option.votes.length}</b></button>)}</div><button className="back-cta" onClick={() => setSelectedDetail(null)}>← Zur Startseite</button></section>{profileEditOpen && <div className="modal-backdrop"><form className="login-card profile-editor" onSubmit={saveProfile}><button className="close-button" type="button" onClick={() => setProfileEditOpen(false)}>×</button><span className="login-icon">😎</span><p className="eyebrow">Dein Auftritt</p><h2>Anzeigename</h2><p>Baue dir deinen offiziellen Malle-Namen.</p><div className="display-name-fields"><label>Titel<select value={draftPrefix} onChange={e => setDraftPrefix(e.target.value)}>{profilePrefixes.map(prefix => <option key={prefix} value={prefix}>{prefix || 'Ohne Titel'}</option>)}</select></label><label>Name<input autoFocus value={draftName} onChange={e => setDraftName(e.target.value)} /></label></div><label className="visibility-toggle"><input type="checkbox" checked={draftVisible} onChange={e => setDraftVisible(e.target.checked)} /><span><strong>In der Crew anzeigen</strong><small>Ausblenden, wenn du nur entwickeln oder organisieren möchtest.</small></span></label><div className="name-preview">Hey, <strong>{draftPrefix}{draftName || 'Malle-Fan'}</strong>!</div><button className="save-button" disabled={!draftName.trim()}>Profil speichern</button></form></div>}
  </main>

  if (selectedDetail === 'chat') return <main className="app-shell detail-page social-page">
    <header className="topbar"><button className="back-button" onClick={() => setSelectedDetail(null)}>← <span>Zurück</span></button><span className="brand"><span className="brand-mark">MHQ</span><span>Malle HQ</span></span></header>
    <section className="detail-hero chat-color"><span className="detail-hero-icon">💬</span><p className="eyebrow">Crew-Chat</p><h1>Was geht?</h1><p>Absprachen, Unsinn und wichtige Durchsagen an einem Ort.</p></section>
    <section className="social-content">{extrasAuthenticated ? <><div className="chat-list">{chatMessages.length ? chatMessages.map(message => <article key={message.id}><span className="avatar" style={{ background: message.color }}>{initials(message.author)}</span><div><strong>{message.author}</strong><p>{message.message}</p><small>{formatDate(message.created_at, { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' })}</small></div></article>) : <p className="empty-state">Noch verdächtig ruhig hier. Schreib die erste Nachricht.</p>}</div><form className="chat-compose" onSubmit={sendChat}><textarea rows={3} placeholder="Nachricht an die Crew …" value={chatText} onChange={e => setChatText(e.target.value)} /><button className="save-button" disabled={!chatText.trim()}>Senden</button></form></> : <p className="login-notice">🔐 Tritt der Crew bei oder melde dich als Harter Kern an, um den Chat zu sehen.</p>}<button className="back-cta" onClick={() => setSelectedDetail(null)}>← Zur Startseite</button></section>
  </main>

  if (selectedDetail === 'highlights') return <main className="app-shell detail-page social-page">
    <header className="topbar"><button className="back-button" onClick={() => setSelectedDetail(null)}>← <span>Zurück</span></button><span className="brand"><span className="brand-mark">MHQ</span><span>Malle HQ</span></span></header>
    <section className="detail-hero highlight-color"><span className="detail-hero-icon">📸</span><p className="eyebrow">Highlights</p><h1>Beweisfotos</h1><p>Die besten, schlimmsten und erinnerungswürdigsten Momente der Crew.</p></section>
    <section className="social-content">{extrasAuthenticated ? <><form className="highlight-form" onSubmit={addHighlight}><label>Titel<input placeholder="z. B. Erste Säule des Tages" value={highlightTitle} onChange={e => setHighlightTitle(e.target.value)} /></label><label>Bild auswählen<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e => setHighlightFile(e.target.files?.[0] || null)} /></label><button className="save-button" disabled={!highlightTitle.trim() || !highlightFile}>Highlight hochladen</button></form><div className="highlight-grid">{highlights.map(item => <article key={item.id}><img src={`${API_BASE}${item.imageUrl}`} alt={item.title} /><div><h2>{item.title}</h2><p>von {item.author}</p></div></article>)}</div>{!highlights.length && <p className="empty-state">Noch keine Highlights – das kann so nicht bleiben.</p>}</> : <p className="login-notice">🔐 Nach dem Beitritt darf jedes Crewmitglied Bilder mit Titel hochladen.</p>}<button className="back-cta" onClick={() => setSelectedDetail(null)}>← Zur Startseite</button></section>
  </main>

  if (selectedDetail === 'archive') return <main className="app-shell detail-page social-page">
    <header className="topbar"><button className="back-button" onClick={() => setSelectedDetail(null)}>← <span>Zurück</span></button><span className="brand"><span className="brand-mark">MHQ</span><span>Malle HQ</span></span></header>
    <section className="detail-hero archive-color"><span className="detail-hero-icon">🧳</span><p className="eyebrow">Reise-Archiv</p><h1>Legenden vergangener Jahre</h1><p>Hier bekommen frühere Eskalationen ihren wohlverdienten Ehrenplatz.</p></section>
    <section className="social-content">{admin && <form className="archive-form" onSubmit={addPastTrip}><h2>Vergangene Reise hinzufügen</h2><div className="archive-fields"><label>Titel<input placeholder="z. B. Malle 2025" value={pastTitle} onChange={e => setPastTitle(e.target.value)} /></label><label>Ziel<input placeholder="Palma de Mallorca" value={pastDestination} onChange={e => setPastDestination(e.target.value)} /></label><label>Start<input type="date" value={pastStart} onChange={e => setPastStart(e.target.value)} /></label><label>Ende<input type="date" value={pastEnd} onChange={e => setPastEnd(e.target.value)} /></label><label className="wide">Erinnerung / Notiz<textarea rows={3} value={pastNote} onChange={e => setPastNote(e.target.value)} /></label></div><button className="save-button" disabled={!pastTitle || !pastDestination || !pastStart || !pastEnd}>Ins Archiv</button></form>}<div className="archive-list">{pastTrips.map(item => <article key={item.id}><span>🌴</span><div><p className="eyebrow">{formatDate(item.start_date, { year: 'numeric' })}</p><h2>{item.title}</h2><strong>📍 {item.destination}</strong><p>{formatDate(item.start_date, { day: 'numeric', month: 'short' })} – {formatDate(item.end_date, { day: 'numeric', month: 'short', year: 'numeric' })}</p>{item.note && <blockquote>{item.note}</blockquote>}</div></article>)}</div>{extrasAuthenticated && !pastTrips.length && <p className="empty-state">Das Reise-Archiv wartet auf seine erste Legende.</p>}{!extrasAuthenticated && <p className="login-notice">🔐 Das Crew-Archiv wird nach dem Beitritt sichtbar.</p>}<button className="back-cta" onClick={() => setSelectedDetail(null)}>← Zur Startseite</button></section>
  </main>

  if (selectedDetail === 'profiles') return <main className="app-shell detail-page profiles-page">
    <header className="topbar"><button className="back-button" onClick={() => setSelectedDetail(null)}>← <span>Zurück</span></button><span className="brand"><span className="brand-mark">MHQ</span><span>Malle HQ</span></span></header>
    <section className="detail-hero profiles-color"><span className="detail-hero-icon">🕵️</span><p className="eyebrow">Mittäter</p><h1>Die üblichen Verdächtigen</h1><p>Alle Crew-Profile, ihre streng geheimen Malle-Namen und völlig seriösen Auszeichnungen.</p></section>
    <section className="profiles-content">
      {ownProfile ? <section className="own-profile-preview"><div><p className="eyebrow">So sehen dich die anderen</p><h2>Dein Crew-Profil</h2></div><button className="profile-gallery-card own-card" onClick={() => setSelectedPerson(ownProfile)}><span className="gallery-avatar" style={{ background: ownProfile.color }}>{ownProfile.avatarUrl ? <img src={`${API_BASE}${ownProfile.avatarUrl}`} alt="" /> : initials(ownProfile.name)}</span><span className="gallery-person"><strong>{ownProfile.name}</strong><small>{ownProfile.nickname || ownProfile.role}</small><em>{ownProfile.flies ? '✈️ Fliegt mit' : '🏖️ App-Gast'}</em></span><span className="gallery-badges">{ownProfile.achievements?.slice(0, 3).map(badge => <b key={badge.id} title={badge.title}>{badge.icon}</b>)}<i>Profil ansehen →</i></span></button><button className="edit-own-profile" onClick={openProfileEditor}>✏️ Profil bearbeiten</button></section> : <section className="profile-login-callout"><span>🔐</span><div><h2>Wo ist dein Fahndungsfoto?</h2><p>Melde dich an oder löse deine Einladung ein, dann erscheint hier deine persönliche Profilvorschau.</p></div><button onClick={() => setLoginOpen(true)}>Anmelden →</button></section>}
      <div className="profiles-heading"><div><p className="eyebrow">Die ganze Bande</p><h2>Alle Mittäter</h2></div><span>{trip.participants.length} sichtbar</span></div>
      <div className="profile-gallery">{galleryProfiles.map(person => <button className="profile-gallery-card" key={person.id} onClick={() => setSelectedPerson(person)}><span className="gallery-avatar" style={{ background: person.color }}>{person.avatarUrl ? <img src={`${API_BASE}${person.avatarUrl}`} alt="" /> : initials(person.name)}</span><span className="gallery-person"><strong>{person.name}</strong><small>{person.nickname || person.role}</small><em>{person.flies ? '✈️ Fliegt mit' : '🏖️ App-Gast'}</em></span><span className="gallery-badges">{person.achievements?.slice(0, 3).map(badge => <b key={badge.id} title={badge.title}>{badge.icon}</b>)}<i>Öffnen →</i></span></button>)}</div>
      {!galleryProfiles.length && <p className="empty-state">Noch keine weiteren Mittäter entdeckt. Verdächtig …</p>}
      <button className="back-cta profiles-back" onClick={() => setSelectedDetail(null)}>← Zur Startseite</button>
    </section>
    {selectedPerson && <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && setSelectedPerson(null)}><article className="profile-card"><button className="close-button" onClick={() => setSelectedPerson(null)}>×</button><span className="profile-avatar" style={{ background: selectedPerson.color }}>{selectedPerson.avatarUrl ? <img src={`${API_BASE}${selectedPerson.avatarUrl}`} alt={`Profilbild von ${selectedPerson.name}`} /> : initials(selectedPerson.name)}</span><p className="eyebrow">So sieht die Crew dieses Profil</p><h2>{selectedPerson.name}</h2>{selectedPerson.nickname && <p className="nickname">„{selectedPerson.nickname}“</p>}<div className="profile-facts"><span><small>Rolle</small><strong>{selectedPerson.role}</strong></span><span><small>Reise</small><strong>{selectedPerson.flies ? '✈️ Fliegt mit' : 'App-Gast'}</strong></span></div><div className="achievement-cards">{selectedPerson.achievements?.map(badge => <span key={badge.id}><b>{badge.icon}</b><strong>{badge.title}</strong></span>)}{!selectedPerson.achievements?.length && <p>Noch skandalös unausgezeichnet.</p>}</div>{selectedPerson.id === profileId && <button className="save-button profile-modal-edit" onClick={() => { setSelectedPerson(null); openProfileEditor() }}>✏️ Mein Profil bearbeiten</button>}</article></div>}
    {loginOpen && <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && setLoginOpen(false)}><form className="login-card" onSubmit={login}><button className="close-button" type="button" onClick={() => setLoginOpen(false)}>×</button><span className="login-icon">🔐</span><p className="eyebrow">Willkommen zurück</p><h2>Anmelden</h2><label>Login-Name<input autoFocus autoCapitalize="none" autoCorrect="off" autoComplete="username webauthn" value={loginName} onChange={e => setLoginName(e.target.value)} /></label><label>Passwort<input type="password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} /></label>{error && <p className="error">{error}</p>}<button className="save-button">Einchecken</button><div className="login-divider"><span>oder</span></div><button type="button" className="passkey-login" onClick={() => void loginWithPasskey()} disabled={passkeyBusy}>{passkeyBusy ? 'Gerät prüft …' : '👆 Mit Passkey / Fingerabdruck'}</button></form></div>}
    {profileEditOpen && <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && setProfileEditOpen(false)}><form className="login-card profile-editor" onSubmit={saveProfile}><button className="close-button" type="button" onClick={() => setProfileEditOpen(false)}>×</button><span className="login-icon">😎</span><p className="eyebrow">Dein Auftritt</p><h2>Anzeigename</h2><label>Profilbild<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e => void uploadAvatar(e.target.files?.[0])} /></label><div className="display-name-fields"><label>Titel<select value={draftPrefix} onChange={e => setDraftPrefix(e.target.value)}>{profilePrefixes.map(prefix => <option key={prefix} value={prefix}>{prefix || 'Ohne Titel'}</option>)}</select></label><label>Name<input autoFocus value={draftName} onChange={e => setDraftName(e.target.value)} /></label></div><label className="visibility-toggle flight-toggle"><input type="checkbox" checked={draftFlies} onChange={e => setDraftFlies(e.target.checked)} /><span><strong>✈️ Ich fliege mit</strong><small>Reserviert deinen Sitzplatz.</small></span></label><label className="visibility-toggle"><input type="checkbox" checked={draftVisible} onChange={e => setDraftVisible(e.target.checked)} /><span><strong>In der Crew anzeigen</strong><small>Steuert deine Sichtbarkeit bei den Mittätern.</small></span></label><div className="name-preview">Hey, <strong>{draftPrefix}{draftName || 'Malle-Fan'}</strong>!</div>{error && <p className="error">{error}</p>}<button className="save-button" disabled={!draftName.trim()}>Profil speichern</button></form></div>}
  </main>

  if (selectedDetail === 'travel') return <main className="app-shell detail-page travel-page">
    <header className="topbar"><button className="back-button" onClick={() => setSelectedDetail(null)}>← <span>Zurück</span></button><span className="brand"><span className="brand-mark">MHQ</span><span>Malle HQ</span></span></header>
    <section className="detail-hero blue"><span className="detail-hero-icon">✈️</span><p className="eyebrow">Anreise</p><h1>Ab auf die Insel</h1><p>{trip.travel}</p></section>
    <section className="detail-content"><div className="flight-overview"><article><span>🛫</span><div><p className="eyebrow">Hinflug</p><h2>{flightDraft.outbound.date ? formatDate(`${flightDraft.outbound.date}T12:00`, { weekday: 'short', day: 'numeric', month: 'long' }) : 'Noch offen'}</h2><strong>{flightDraft.outbound.time || '–'} Uhr · {flightDraft.outbound.airport || 'Flughafen folgt'}</strong><small>{[flightDraft.outbound.flightNumber, flightDraft.outbound.terminal && `Terminal ${flightDraft.outbound.terminal}`, flightDraft.outbound.gate && `Gate ${flightDraft.outbound.gate}`].filter(Boolean).join(' · ') || 'Flugdetails folgen'}</small></div></article><article><span>🛋️</span><div><p className="eyebrow">Treffen</p><h2>{flightDraft.airportMeetingTime || '–'} Uhr</h2><strong>{flightDraft.outbound.airport || 'Am Abflughafen'}</strong><small>Gemeinsamer Treffpunkt vor dem Abflug</small></div></article><article><span>🛏️</span><div><p className="eyebrow">Rückflug</p><h2>{flightDraft.return.date ? formatDate(`${flightDraft.return.date}T12:00`, { weekday: 'short', day: 'numeric', month: 'long' }) : 'Noch offen'}</h2><strong>{flightDraft.return.time || '–'} Uhr · {flightDraft.return.airport || 'Flughafen folgt'}</strong><small>{[flightDraft.return.flightNumber, flightDraft.return.terminal && `Terminal ${flightDraft.return.terminal}`, flightDraft.return.gate && `Gate ${flightDraft.return.gate}`].filter(Boolean).join(' · ') || 'Flugdetails folgen'}</small></div></article></div>
      {admin && <section className="card-editor"><div className="card-editor-heading"><span>✏️</span><div><p className="eyebrow">Nur für den Harten Kern</p><h2>Flugdaten eintragen</h2><p>Einmal ordentlich ausfüllen – Bierbert bringt alles automatisch in Form.</p></div></div><div className="flight-edit-grid">{(['outbound', 'return'] as const).map((leg, index) => <fieldset key={leg}><legend>{index === 0 ? '🛫 Hinflug' : '🛏️ Rückflug'}</legend><div className="flight-fields"><label>Datum<input type="date" value={flightDraft[leg].date} onChange={e => changeFlight(leg, 'date', e.target.value)} /></label><label>Abflugzeit<input type="time" value={flightDraft[leg].time} onChange={e => changeFlight(leg, 'time', e.target.value)} /></label><label className="wide">Flughafen<input placeholder={leg === 'outbound' ? 'z. B. Düsseldorf (DUS)' : 'Palma de Mallorca (PMI)'} value={flightDraft[leg].airport} onChange={e => changeFlight(leg, 'airport', e.target.value)} /></label><label>Flugnummer<input placeholder="z. B. EW 9584" value={flightDraft[leg].flightNumber} onChange={e => changeFlight(leg, 'flightNumber', e.target.value)} /></label><label>Terminal<input placeholder="z. B. B" value={flightDraft[leg].terminal} onChange={e => changeFlight(leg, 'terminal', e.target.value)} /></label><label>Gate<input placeholder="z. B. A42" value={flightDraft[leg].gate} onChange={e => changeFlight(leg, 'gate', e.target.value)} /></label></div></fieldset>)}</div><label className="meeting-time-field"><span>⏰</span><span><strong>Wann treffen wir uns am Flughafen?</strong><small>Die Uhrzeit vor dem Hinflug</small></span><input type="time" value={flightDraft.airportMeetingTime} onChange={e => { setTravelSaved(false); setFlightDraft(current => ({ ...current, airportMeetingTime: e.target.value })) }} /></label><label className="travel-notes">Zusätzliche Reisehinweise<textarea rows={4} value={trip.travelDetails} onChange={e => setTrip(current => ({ ...current, travelDetails: e.target.value }))} placeholder="Gepäck, Transfer, Sitzplätze oder sonstige Hinweise …" /></label><button className="save-button flight-save" onClick={() => void saveFlightPlan()}>{travelSaved ? 'Flugdaten gespeichert ✓' : 'Flugdaten speichern'}</button></section>}
      {!admin && trip.travelDetails && <div className="detail-copy"><p>{trip.travelDetails}</p></div>}<button className="back-cta" onClick={() => setSelectedDetail(null)}>← Zur Startseite</button></section>
  </main>

  if (activeDetail) return <main className="app-shell detail-page">
    <header className="topbar"><button className="back-button" onClick={() => setSelectedDetail(null)}>← <span>Zurück</span></button><span className="brand"><span className="brand-mark">MHQ</span><span>Malle HQ</span></span></header>
    <section className={`detail-hero ${activeDetail.color}`}><span className="detail-hero-icon">{activeDetail.icon}</span><p className="eyebrow">{activeDetail.label}</p><h1>{activeDetail.title}</h1><p>{trip[activeDetail.key]}</p></section>
    <section className="detail-content"><p className="eyebrow">Alle Details</p><h2>{activeDetail.label} im Überblick</h2><div className="detail-copy">{String(trip[activeDetail.detailKey]).split('\n').map((line, index) => <p key={index}>{line || <br />}</p>)}</div>{admin && <section className="card-editor compact-editor"><div className="card-editor-heading"><span>✏️</span><div><p className="eyebrow">Direkt in dieser Card</p><h2>{activeDetail.label} bearbeiten</h2></div></div><label>Kurztext auf der Startseite<textarea rows={2} value={String(trip[activeDetail.key])} onChange={e => setTrip(current => ({ ...current, [activeDetail.key]: e.target.value }))} /></label><label>Details in dieser Card<textarea rows={5} value={String(trip[activeDetail.detailKey])} onChange={e => setTrip(current => ({ ...current, [activeDetail.detailKey]: e.target.value }))} /></label><button className="save-button" onClick={() => void saveCloud(trip)}>Änderungen speichern</button></section>}<button className="back-cta" onClick={() => setSelectedDetail(null)}>← Zur Startseite</button></section>
  </main>

  return <main className="app-shell">
    <header className="topbar"><a className="brand" href="#top"><span className="brand-mark">MHQ</span><span>Malle HQ</span></a><button className="profile profile-own" onClick={openProfileEditor} title="Eigenes Profil bearbeiten">{initials(displayName)}</button></header>
    <section className="hero" id="top"><div className="sun" /><div className="hero-copy"><p className="eyebrow">Bierbert sagt</p><h1>Hey <span>{displayName}.</span></h1><p className="hero-question">{heroQuestion}</p><p className="intro">Alle Infos, alle Termine, eine Crew.<br />Bierbert hält euch auf Kurs.</p></div><img className="bierbert" src={bierbert} alt="Bierbert, das gut gelaunte Malle-HQ-Maskottchen" /></section>
    <section className="countdown-card"><div className="countdown-heading"><div><p className="eyebrow">Abflug in</p><h2>Der Countdown läuft</h2></div><span className="palm">🌴</span></div><div className="countdown">{Object.entries(countdown).map(([label, value]) => <div className="time-unit" key={label}><strong>{String(value).padStart(2, '0')}</strong><span>{labels[label]}</span></div>)}</div></section>
    <section className="trip-card"><div className="trip-date"><strong>{formatDate(trip.startDate, { day: '2-digit' })}</strong><span>{formatDate(trip.startDate, { month: 'short' }).replace('.', '').toUpperCase()}</span></div><div className="trip-copy"><p className="eyebrow">Unser Trip · {formatDate(trip.startDate, { year: 'numeric' })}</p><h2>{trip.destination}</h2><p>{formatDate(trip.startDate, { day: 'numeric', month: 'short' })} – {formatDate(trip.endDate, { day: 'numeric', month: 'short' })} · {duration}</p></div><a className="arrow-link" href="#reise">↓</a></section>
    <button className="install-app-button" onClick={installApp}><span className="install-icon">📲</span><span><small>Für Android & iPhone</small><strong>Malle HQ als App installieren</strong></span><b>Installieren →</b></button>
    <button className={`push-app-button ${pushEnabled ? 'enabled' : ''}`} onClick={enablePush} disabled={pushEnabled}><span className="install-icon">{pushEnabled ? '🔔' : '📣'}</span><span><small>Bierbert hält dich auf dem Laufenden</small><strong>{pushEnabled ? 'Push-Nachrichten sind aktiv' : 'Push-Nachrichten aktivieren'}</strong></span><b>{pushEnabled ? 'Aktiv ✓' : 'Erlauben →'}</b></button>
    <section className="details-section" id="reise"><div className="section-heading"><div><p className="eyebrow">Alles an einem Ort</p><h2>{trip.title}</h2></div><span>Olé! 🍻</span></div><div className="details-grid">{detailCards.map(card => <button className={`detail-card ${card.color}`} key={card.key} onClick={() => { setSelectedDetail(card.key); window.scrollTo(0, 0) }}><span className="detail-icon">{card.icon}</span><div><p className="eyebrow">{card.label}</p><h3>{card.title}</h3><p>{trip[card.key]}</p><span className="card-link">Details ansehen →</span></div></button>)}<button className="detail-card planning-color planning-card" onClick={() => { setSelectedDetail('planning'); window.scrollTo(0, 0) }}><span className="detail-icon">🗓️</span><div><p className="eyebrow">Planungstreffen</p><h3>Wann passt’s?</h3><p>{trip.planningMeeting}</p><span className="card-link">Termin finden →</span></div></button><button className="detail-card live-color planning-card" onClick={() => { setSelectedDetail('live'); window.scrollTo(0, 0) }}><span className="detail-icon">🎤</span><div><p className="eyebrow">Malle-Live-Auftritte</p><h3>Wer spielt wann?</h3><p>Bestätigte Acts sammeln und keinen Auftritt verpassen.</p><span className="card-link">Auftritte ansehen →</span></div></button><button className="detail-card chat-color planning-card" onClick={() => { setSelectedDetail('chat'); void loadExtras(); window.scrollTo(0, 0) }}><span className="detail-icon">💬</span><div><p className="eyebrow">Crew-Chat</p><h3>Was geht?</h3><p>Kurze Absprachen und wichtige Durchsagen für alle.</p><span className="card-link">Chat öffnen →</span></div></button><button className="detail-card highlight-color planning-card" onClick={() => { setSelectedDetail('highlights'); void loadExtras(); window.scrollTo(0, 0) }}><span className="detail-icon">📸</span><div><p className="eyebrow">Highlights</p><h3>Beweisfotos</h3><p>Bilder mit Titel hochladen – erlaubt für die ganze Crew.</p><span className="card-link">Galerie öffnen →</span></div></button><button className="detail-card archive-color planning-card" onClick={() => { setSelectedDetail('archive'); void loadExtras(); window.scrollTo(0, 0) }}><span className="detail-icon">🧳</span><div><p className="eyebrow">Reise-Archiv</p><h3>Frühere Eskalationen</h3><p>Vergangene Reisen und ihre Geschichten sammeln.</p><span className="card-link">Archiv öffnen →</span></div></button></div></section>
    <button className="mittaeter-home-card" onClick={() => { setSelectedDetail('profiles'); window.scrollTo(0, 0) }}><span>🕵️</span><span><small>Die ganze Bande</small><strong>Mittäter</strong><p>Profile, Malle-Namen und Auszeichnungen der Crew ansehen.</p></span><b>{trip.participants.length} Profile →</b></button>
    <section className="crew-section"><div className="section-heading"><div><p className="eyebrow">Unsere Truppe</p><h2>Wer ist dabei?</h2></div><span>{trip.participants.length} App-Profile</span></div><div className="crew-list">{trip.participants.map(person => <button className="crew-member" key={person.id} onClick={() => setSelectedPerson(person)}><span className="avatar" style={{ background: person.color }}>{person.avatarUrl ? <img src={`${API_BASE}${person.avatarUrl}`} alt="" /> : initials(person.name)}</span><span className="crew-name"><strong>{person.name}</strong><small>{person.nickname || person.role}</small></span><span className={`status ${person.flies ? '' : 'open'}`}>{person.flies ? '✈️ Fliegt mit' : 'App-Gast'}</span></button>)}</div>
      <section className="malle-plane"><div className="plane-heading"><span>✈️</span><div><p className="eyebrow">Direktflug nach Palma de Mallorca</p><h2>Bierberts Sitzordnung</h2><p>{flyers.length ? `${flyers.length} ${flyers.length === 1 ? 'Person sitzt' : 'Personen sitzen'} schon im Flieger.` : 'Noch ist der Flieger leer – ab ins Profil und Sitzplatz sichern!'}</p></div></div><div className="plane-body"><div className="cockpit"><span>PMI</span><small>Palma</small></div><div className="plane-seats">{Array.from({ length: Math.max(8, flyers.length) }, (_, index) => { const person = flyers[index]; return person ? <button className="plane-seat occupied" key={person.id} onClick={() => setSelectedPerson(person)} title={`${person.name} fliegt mit`}><span className="seat-avatar" style={{ background: person.color }}>{person.avatarUrl ? <img src={`${API_BASE}${person.avatarUrl}`} alt={`Profilbild von ${person.name}`} /> : <span>👤</span>}</span><strong>{person.name}</strong><small>{String(Math.floor(index / 2) + 1).padStart(2, '0')}{index % 2 ? 'B' : 'A'}</small></button> : <div className="plane-seat empty" key={`empty-${index}`}><span>+</span><strong>Frei</strong><small>{String(Math.floor(index / 2) + 1).padStart(2, '0')}{index % 2 ? 'B' : 'A'}</small></div> })}</div><div className="plane-tail">🌴</div></div><button className="my-flight-button" onClick={openProfileEditor}>{trip.myProfile.flies ? '✅ Mein Sitzplatz ist reserviert' : '✈️ Ich fliege mit – im Profil eintragen'}</button></section>
      <button className="invite-cta" onClick={() => { setInviteOpen(true); setInviteCode(''); setError('') }}><span>✉️</span><span><strong>Du hast eine Einladung?</strong><small>Code eingeben und zur Crew stoßen</small></span><b>→</b></button></section>
    <section className="notes-card"><span className="notes-icon">📝</span><div><p className="eyebrow">Notizen</p><h2>Was noch wichtig ist</h2><p>{trip.notes}</p></div></section>
    {admin && <section className="admin-panel core-hub"><div className="admin-heading"><div><p className="eyebrow">Harter-Kern-Zentrale</p><h2>Was möchtest du pflegen?</h2><p>Die Reiseinfos bearbeitest du jetzt dort, wo sie hingehören: direkt in den jeweiligen Cards.</p></div></div><div className="core-actions">{detailCards.map(card => <button key={card.key} onClick={() => { setSelectedDetail(card.key); window.scrollTo(0, 0) }}><span className={card.color}>{card.icon}</span><span><strong>{card.label}</strong><small>Card öffnen und bearbeiten</small></span><b>→</b></button>)}</div><div className="invite-admin"><div><p className="eyebrow">Crew erweitern</p><h3>Einladungen</h3><p>Erstelle einen persönlichen Code und entscheide, ob die Person ebenfalls zum Harten Kern gehört.</p></div><div className="invite-create"><input placeholder="Name der Person (optional)" value={newRecipient} onChange={e => setNewRecipient(e.target.value)} /><select aria-label="Rolle der eingeladenen Person" value={newInviteRole} onChange={e => setNewInviteRole(e.target.value)}><option>Crewmitglied</option><option>Harter Kern</option></select><button className="save-button" onClick={createInvite}>Code erstellen</button></div>{trip.invitations.length > 0 && <div className="invite-list">{trip.invitations.map(invite => <div className="invite-row" key={invite.id}><span><strong>{invite.recipient}</strong><small>{invite.code} · {invite.role}</small></span><span className={`status ${invite.used ? '' : 'open'}`}>{invite.used ? 'Beigetreten' : 'Offen'}</span><button onClick={() => copyInvite(invite.code)} disabled={invite.used}>{copied === invite.code ? 'Kopiert ✓' : 'Teilen'}</button></div>)}</div>}</div><div className="password-reset-admin"><p className="eyebrow">Passwort-Hilfe</p><h3>Zugang wiederherstellen</h3><p>Wähle genau das betroffene Profil. Der neue Code gilt einmalig und 24 Stunden.</p><div>{accountProfiles.map(target => <article key={target.id}><span><strong>{target.name}</strong><small>{target.role}{target.visible ? '' : ' · ausgeblendet'}</small></span>{resetCodes[target.id] ? <button className="reset-code" onClick={() => navigator.clipboard.writeText(resetCodes[target.id])}>{resetCodes[target.id]} · kopieren</button> : <button onClick={() => void generatePasswordReset(target)}>Neuen Code erzeugen</button>}</article>)}</div></div></section>}
    {selectedPerson && <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && setSelectedPerson(null)}><article className="profile-card"><button className="close-button" onClick={() => setSelectedPerson(null)}>×</button><span className="profile-avatar" style={{ background: selectedPerson.color }}>{selectedPerson.avatarUrl ? <img src={`${API_BASE}${selectedPerson.avatarUrl}`} alt={`Profilbild von ${selectedPerson.name}`} /> : initials(selectedPerson.name)}</span><p className="eyebrow">Crew-Profil</p><h2>{selectedPerson.name}</h2>{selectedPerson.nickname && <p className="nickname">„{selectedPerson.nickname}“</p>}<div className="profile-facts"><span><small>Rolle</small><strong>{selectedPerson.role}</strong></span><span><small>Reise</small><strong>{selectedPerson.flies ? '✈️ Fliegt mit' : 'App-Gast'}</strong></span></div><div className="achievement-cards">{selectedPerson.achievements?.map(badge => <span key={badge.id}><b>{badge.icon}</b><strong>{badge.title}</strong></span>)}{!selectedPerson.achievements?.length && <p>Noch skandalös unausgezeichnet.</p>}</div>{admin && <div className="achievement-award"><p className="eyebrow">Quatsch-Auszeichnung verleihen</p><div className="achievement-presets">{achievementPresets.map(preset => <button key={preset.title} onClick={() => { setAchievementIcon(preset.icon); setAchievementTitle(preset.title) }}><span>{preset.icon}</span>{preset.title}</button>)}</div><div><select aria-label="Symbol" value={achievementIcon} onChange={e => setAchievementIcon(e.target.value)}><option>🏆</option><option>🍻</option><option>✈️</option><option>🌴</option><option>👑</option><option>🥴</option><option>🍹</option><option>🎉</option></select><input placeholder="Oder eigenen Titel eintragen …" value={achievementTitle} onChange={e => setAchievementTitle(e.target.value)} /><button onClick={() => void awardAchievement()} disabled={!achievementTitle.trim()}>Verleihen</button></div></div>}</article></div>}
    {profileEditOpen && <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && setProfileEditOpen(false)}><form className="login-card profile-editor" onSubmit={saveProfile}><button className="close-button" type="button" onClick={() => setProfileEditOpen(false)}>×</button><span className="login-icon">😎</span><p className="eyebrow">Dein Auftritt</p><h2>Anzeigename</h2><p>Baue dir deinen offiziellen Malle-Namen und sag Bierbert, ob er dir einen Sitz reservieren soll.</p><label>Profilbild<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e => void uploadAvatar(e.target.files?.[0])} /></label><div className="display-name-fields"><label>Titel<select value={draftPrefix} onChange={e => setDraftPrefix(e.target.value)}>{profilePrefixes.map(prefix => <option key={prefix} value={prefix}>{prefix || 'Ohne Titel'}</option>)}</select></label><label>Name<input autoFocus value={draftName} onChange={e => setDraftName(e.target.value)} /></label></div><label className="visibility-toggle flight-toggle"><input type="checkbox" checked={draftFlies} onChange={e => setDraftFlies(e.target.checked)} /><span><strong>✈️ Ich fliege mit nach Mallorca</strong><small>Dann erscheint dein Profil auf einem Sitzplatz im Flieger.</small></span></label><label className="visibility-toggle"><input type="checkbox" checked={draftVisible} onChange={e => setDraftVisible(e.target.checked)} /><span><strong>In der Crew anzeigen</strong><small>Ausblenden, wenn du nur entwickeln oder organisieren möchtest.</small></span></label><div className="name-preview">Hey, <strong>{draftPrefix}{draftName || 'Malle-Fan'}</strong>!</div><div className="account-actions"><button type="button" className="passkey-button" onClick={() => void registerPasskey()} disabled={passkeyBusy}>{passkeyBusy ? 'Gerät prüft …' : '🔐 Passkey / Fingerabdruck einrichten'}</button><button type="button" className="password-change-button" onClick={() => { setProfileEditOpen(false); setChangePasswordOpen(true); setError('') }}>🔑 Passwort ändern</button><button type="button" className="logout-button" onClick={() => void logout()}>→ Logout</button><small>Du bleibst auf diesem Gerät dauerhaft angemeldet, bis du dich ausloggst.</small></div>{error && <p className="error">{error}</p>}<button className="save-button" disabled={!draftName.trim()}>Profil speichern</button></form></div>}
    {installHelpOpen && <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && setInstallHelpOpen(false)}><article className="login-card install-help"><button className="close-button" onClick={() => setInstallHelpOpen(false)}>×</button><span className="login-icon">📲</span><p className="eyebrow">Malle HQ mitnehmen</p><h2>Als App installieren</h2><div className="install-steps"><div><strong>Auf dem iPhone</strong><p>In Safari unten auf „Teilen“ tippen und anschließend „Zum Home-Bildschirm“ wählen.</p></div><div><strong>Auf Android</strong><p>Im Browser-Menü „App installieren“ oder „Zum Startbildschirm hinzufügen“ wählen.</p></div></div><button className="save-button" onClick={() => setInstallHelpOpen(false)}>Alles klar</button></article></div>}
    {inviteOpen && <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && setInviteOpen(false)}>{inviteIsValid ? <form className="login-card" onSubmit={acceptInvite}><button className="close-button" type="button" onClick={() => setInviteOpen(false)}>×</button><span className="login-icon">🌴</span><p className="eyebrow">Fast eingecheckt</p><h2>Profil & Zugang</h2><p>Wähle jetzt auch deine persönlichen Zugangsdaten.</p><label>Anzeigename<input autoFocus value={inviteName} onChange={e => setInviteName(e.target.value)} /></label><label>Spitzname <small>optional</small><input value={inviteNickname} onChange={e => setInviteNickname(e.target.value)} /></label><label>Login-Name<input autoCapitalize="none" autoCorrect="off" placeholder="z. B. andy27" value={inviteLoginName} onChange={e => setInviteLoginName(e.target.value)} /></label><label>Eigenes Passwort <small>mindestens 8 Zeichen</small><input type="password" value={invitePassword} onChange={e => setInvitePassword(e.target.value)} /></label><label>Deine Antwort<select value={inviteStatus} onChange={e => setInviteStatus(e.target.value as Rsvp)}><option>Dabei</option><option>Vielleicht</option><option>Abgesagt</option></select></label><label className="visibility-toggle flight-toggle"><input type="checkbox" checked={inviteFlies} onChange={e => setInviteFlies(e.target.checked)} /><span><strong>✈️ Ich fliege mit</strong><small>Reserviert direkt einen Platz in Bierberts Sitzordnung.</small></span></label>{error && <p className="error">{error}</p>}<button className="save-button">Profil und Zugang erstellen</button></form> : <div className="login-card"><button className="close-button" onClick={() => setInviteOpen(false)}>×</button><span className="login-icon">✉️</span><p className="eyebrow">Einladung</p><h2>Willkommen an Bord</h2><p>Gib den Code aus deiner Einladung ein.</p><label>Einladungscode<input autoFocus placeholder="MALLE-XXXXXXXX" value={inviteCode} onChange={e => { setInviteCode(e.target.value.toUpperCase()); setError('') }} onKeyDown={e => e.key === 'Enter' && checkInvite()} /></label>{error && <p className="error">{error}</p>}<button className="save-button" type="button" onClick={checkInvite}>Code prüfen</button></div>}</div>}
    {loginOpen && <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && setLoginOpen(false)}><form className="login-card" onSubmit={login}><button className="close-button" type="button" onClick={() => setLoginOpen(false)}>×</button><span className="login-icon">🔐</span><p className="eyebrow">{setupRequired ? 'Einmalige Einrichtung' : 'Willkommen zurück'}</p><h2>{setupRequired ? 'Dein Harter-Kern-Zugang' : 'Anmelden'}</h2><p>{setupRequired ? 'Lege deinen persönlichen Login fest. Der bisherige Code wird nur dieses eine Mal gebraucht.' : 'Melde dich einmal an und bleib auf diesem Gerät eingeloggt.'}</p>{setupRequired && <><label>Anzeigename<input value={setupDisplayName} placeholder="z. B. Roni" onChange={e => setSetupDisplayName(e.target.value)} /></label><label>Einmaliger Einrichtungscode<input type="password" value={setupCode} onChange={e => { setSetupCode(e.target.value); setError('') }} /></label></>}<label>Login-Name<input autoFocus={!setupRequired} autoCapitalize="none" autoCorrect="off" autoComplete="username webauthn" value={loginName} onChange={e => { setLoginName(e.target.value); setError('') }} /></label><label>Passwort <small>{setupRequired ? 'mindestens 8 Zeichen' : ''}</small><input type="password" autoComplete="current-password" value={password} onChange={e => { setPassword(e.target.value); setError('') }} /></label>{error && <p className="error">{error}</p>}<button className="save-button">{setupRequired ? 'Persönlichen Zugang anlegen' : 'Einchecken'}</button>{!setupRequired && <><button type="button" className="forgot-button" onClick={() => { setLoginOpen(false); setForgotOpen(true); setError('') }}>Passwort vergessen?</button><div className="login-divider"><span>oder</span></div><button type="button" className="passkey-login" onClick={() => void loginWithPasskey()} disabled={passkeyBusy}>{passkeyBusy ? 'Gerät prüft …' : '👆 Mit Passkey / Fingerabdruck'}</button></>}</form></div>}
    {forgotOpen && <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && setForgotOpen(false)}><form className="login-card" onSubmit={redeemPasswordReset}><button className="close-button" type="button" onClick={() => setForgotOpen(false)}>×</button><span className="login-icon">🛟</span><p className="eyebrow">Bierberts Rettungsring</p><h2>Neues Passwort</h2><p>Bitte den Harten Kern um einen Wiederherstellungscode für genau dein Profil. Er gilt einmalig und 24 Stunden.</p><label>Wiederherstellungscode<input autoFocus placeholder="MALLE-PW-…" value={recoveryCode} onChange={e => setRecoveryCode(e.target.value.toUpperCase())} /></label><label>Neues Passwort <small>mindestens 8 Zeichen</small><input type="password" value={recoveryPassword} onChange={e => setRecoveryPassword(e.target.value)} /></label><label>Neues Passwort wiederholen<input type="password" value={recoveryConfirm} onChange={e => setRecoveryConfirm(e.target.value)} /></label>{error && <p className="error">{error}</p>}<button className="save-button" disabled={!recoveryCode || recoveryPassword.length < 8}>Passwort erneuern & einloggen</button></form></div>}
    {changePasswordOpen && <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && setChangePasswordOpen(false)}><form className="login-card" onSubmit={changePassword}><button className="close-button" type="button" onClick={() => setChangePasswordOpen(false)}>×</button><span className="login-icon">🔑</span><p className="eyebrow">Zugang absichern</p><h2>Passwort ändern</h2><label>Bisheriges Passwort<input autoFocus type="password" value={currentPassword} onChange={e => setCurrentPassword(e.target.value)} /></label><label>Neues Passwort <small>mindestens 8 Zeichen</small><input type="password" value={newPassword} onChange={e => setNewPassword(e.target.value)} /></label><label>Neues Passwort wiederholen<input type="password" value={newPasswordConfirm} onChange={e => setNewPasswordConfirm(e.target.value)} /></label>{error && <p className="error">{error}</p>}<button className="save-button" disabled={!currentPassword || newPassword.length < 8}>Passwort speichern</button></form></div>}
    {onboardingStep !== null && <div className="onboarding"><button className="onboarding-skip" onClick={finishOnboarding}>Überspringen</button><div className="onboarding-card"><div className="onboarding-bierbert"><img src={bierbert} alt="Bierbert" /><span>{onboardingSteps[onboardingStep].icon}</span></div><p className="eyebrow">Bierbert erklärt · {onboardingStep + 1}/{onboardingSteps.length}</p><h1>{onboardingSteps[onboardingStep].title}</h1><p>{onboardingSteps[onboardingStep].text}</p><div className="onboarding-dots">{onboardingSteps.map((_, index) => <span className={index === onboardingStep ? 'active' : ''} key={index} />)}</div><button className="save-button" onClick={() => { if (onboardingStep === onboardingSteps.length - 1) { finishOnboarding(); setInviteCode(''); setInviteOpen(true) } else setOnboardingStep(onboardingStep + 1) }}>{onboardingStep === onboardingSteps.length - 1 ? 'Mit Einladungscode einchecken →' : 'Weiter →'}</button></div></div>}
    <footer>Mit ❤️ und Vorfreude für die beste Crew. <button onClick={() => { setLoginOpen(true); setError('') }}>Anmelden</button></footer>
  </main>
}
export default App
